# Generated by Django 2.2 on 2019-04-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(default='test'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='my location test', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='name test', max_length=120),
        ),
    ]
