# Generated by Django 2.2 on 2019-05-07 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20190506_2228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
